name = "rolldorado-bonus-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldorado-bonus.pt"
HMAC_KEY = "52d9dfd24792907047a87721f849d4e86c6c6c051c607a1d07cce5bc36850d39"
COOKIE_NAME = "1dy"
PLAY_PATH = "visit"
BUTTON_ID = "pc969ef42fb3202d2217204a3d766edaf"
GATE_SALT = "bcf37f328313d064"
